### ISSUE TITLE
KeyError 'license' 

### ISSUE THREAD

**Issue by mafiaboyzdj** [Diazole/vdocipher-dl#2]
hi, @Diazole
built the wvd, tried 2/3 CDMs got the same error.
Is it because of dead CDMs?

tried on both Python 3.10 and 3.8, issue persists

also, what argument did you add in ANDROID , when using pywidevine create device?

just -t ANDROID ?

![cdm](https://user-images.githubusercontent.com/114650906/192976163-ca151f47-c59d-4c9e-a4b5-43b7c7d90fc0.png)

**Comment by mafiaboyzdj** [comment]
with this in code

if not req.ok:
print("license failed: \n", req.text)
exit()
resp = req.json()
return resp['license']

I get the error code 2022: License Creation failed.

**Comment by Diazole** [comment]
Banned CDM.
