### ISSUE TITLE
href error

### ISSUE THREAD

**Issue by sahilflashx** [Diazole/vdocipher-dl#4]

**Comment by Diazole** [comment]
You're using the wrong token. That token you've posted contains your build info for your CDM.

```
Zenfone Max Pro M1
google/walleye/walleye:8.1.0/OPM1.171019.011/4448085:user/release-keys
widevine_cdm_version 15.0.0
OEMCrypto Level3 Code 8159 Apr 18 2019 19:27:352
```
You must use the first token sent to the license server.

**Comment by sahilflashx** [comment]
can you please delete my build info from your comment please
